services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MCP_ENDPOINT=http://mcp-gateway:8811  # Fixed: matches app.js expectation
      - MODEL_RUNNER_URL=${MODEL_RUNNER_URL:-}  # Will be set by models section
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL:-}  # Will be set by models section
    depends_on:
      - mcp-gateway
      - gemma  # Ensure model is ready
    models:
      gemma:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8811:8811"
    command:
      - --transport=sse
      - --servers=duckduckgo
      - --tools=search,fetch_content

models:
  gemma:
    model: ai/gemma3:4B-Q4_0
    context_size: 8192