services:
  simple-agent:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MCP_ENDPOINT=http://mcp-gateway:8811/sse
      - MODEL_RUNNER_URL=${MODEL_RUNNER_URL}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL}
      - NODE_ENV=production
    depends_on:
      - mcp-gateway
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    models:
      qwen3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

  mcp-gateway:
    # MCP gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      # Only use DuckDuckGo for now to avoid filesystem volume issues
      - --servers=duckduckgo
    volumes:
      # Mount sample data for future filesystem support
      - ./sample-data:/mnt/sample-data:ro

models:
  qwen3:
    # Use your already downloaded model
    model: ai/qwen3:8B-Q4_0
    context_size: 16384  # Larger context for the 8B model
    # The 8B model provides better performance than 4B or 1.5B variants
