services:
  simple-agent:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MCP_ENDPOINT=http://mcp-gateway:8811/sse
      - MODEL_RUNNER_URL=http://host.docker.internal:12434/v1
      - MODEL_RUNNER_MODEL=qwen3
      - NODE_ENV=production
    depends_on:
      - mcp-gateway
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Remove automatic model management - use custom endpoint instead

  mcp-gateway:
    # MCP gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      # Only use DuckDuckGo for now to avoid filesystem volume issues
      - --servers=duckduckgo
    volumes:
      # Mount sample data for future filesystem support
      - ./sample-data:/mnt/sample-data:ro

# Remove models section to use custom endpoint on port 12434
